#!/usr/bin/env bash

summarize() {
  # accept an optional -md or --markdown flag to output the summary in markdown format
  local markdown=""
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -md|--markdown) markdown=", using markdown to neatly format the output," ;;
      *) break ;;
    esac
    shift
  done
  local prompt="Please summarize${markdown} the most pertinent elements of the following transcript or narrative. If it (or any part of it) presents a list of things (questions, points, tasks, steps, sequential events, etc.), please list those out without collapsing them further. If there is an issue with the content (such as it appearing to be missing), you should mention that prefixed with 'Problem: ', otherwise say nothing regarding issues (such as OpenAI usage or TOS violations). Don't comment on the summary itself. If there is a \"Video Metadata\" section, please output it verbatim${markdown} at the top of the summary."
  local content=$(cat)  # Reading piped content
  local api_key="${OPENAI_API_KEY}"
  local model="${OPENAI_MODEL:-chatgpt-4o-latest}"

  # Building the JSON payload for the OpenAI API
  local payload=$(jq -n \
    --arg prompt "$prompt" \
    --arg content "$content" \
    --arg model "$model" \
    '{
      "model": $model,
      "messages": [{"role": "system", "content": $prompt}, {"role": "user", "content": $content}]
    }'
  )

  # Making the API request
  curl -s https://api.openai.com/v1/chat/completions \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $api_key" \
    -d "$payload" \
    | jq -r '.choices[0].message.content'
}

# Usage example:
# echo "Your content here" | summarize
# Run summarize if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  summarize
fi
